server:
  port:8081
spring:
  application:
  name:CustomerService
  datasource:
    url:jdbc:postgresql://dpg-d51r18emcj7s73eigpqg-a.origon-postgres.render.com:5432/customerservice_8lzw
    username:customerservice_8lzw_user
    password:32cfmstZLQNMyLmNf9dPCDiMF3nOfJHR
    driver-class-name:org.postgresql.Driver
  jpa:
  show-sql:true
  hibernate:
  ddl-auto:update
  eureka:
    instance:
      hostname:localhost
